import { pgEnum } from "drizzle-orm/pg-core";

export const authorityTypeEnum = pgEnum("authority_type", ["state_agency","tribal","federal","land_trust","ngo","private_landowner"]);
export const waterTypeEnum = pgEnum("water_type", ["lake","reservoir","river","stream","creek","pond","marina","impoundment"]);
export const hydroRelationEnum = pgEnum("hydro_relation", ["outlet","tributary_of"]);
export const wbaRoleEnum = pgEnum("wba_role", ["take_rules","access","land_management","permit_issuer","none"]);
export const flowDirEnum = pgEnum("flow_dir", ["upstream","downstream"]);
export const distUnitEnum = pgEnum("dist_unit", ["ft","yd","m"]);
export const zoneKindEnum = pgEnum("zone_kind", ["district","region","county","tributary_group","closed_area","swim_area","jurisdiction","named_area","buffer"]);
export const speciesCategoryEnum = pgEnum("species_category", ["trout","char","salmon","bass","warmwater","panfish","catfish","sucker","minnow","sculpin","hybrid","other"]);
export const nativeStatusEnum = pgEnum("native_status", ["native","introduced","stocked","stocked_hybrid"]);
export const presenceEnum = pgEnum("presence", ["native","stocked","introduced","historical"]);
export const mgmtCategoryEnum = pgEnum("mgmt_category", ["community_fishing_pond","trophy_water","general"]);
export const documentTypeEnum = pgEnum("document_type", ["webpage","pdf","booklet","gis","api"]);
export const instrumentTypeEnum = pgEnum("instrument_type", ["commission_reg","admin_code","statute","booklet","guide","webpage","gis","tribal_ordinance","emergency_order","directors_order","hotline"]);
export const authorityLevelEnum = pgEnum("authority_level", ["primary_regulatory","agency_mirror","third_party"]);
export const fetchStatusEnum = pgEnum("fetch_status", ["ok","failed_binary","failed_404","manual"]);
export const ruleTypeEnum = pgEnum("rule_type", ["season","bag","size_limit","gear_method","fishing_hours","closure","handling","vessel","ais","documentation","license","definition","special"]);
export const rulePolarityEnum = pgEnum("rule_polarity", ["applies","asserts_none","excludes"]);
export const basisEnum = pgEnum("basis", ["explicit","statewide_default","inherited"]);
export const anglerClassEnum = pgEnum("angler_class", ["any","tribal_member","non_tribal","spouse_of_member","minor","senior","disabled","resident","nonresident","active_military","youth"]);
export const confidenceEnum = pgEnum("confidence", ["low","medium","high"]);
export const statusEnum = pgEnum("status", ["draft","needs_review","verified","published","proposed","superseded","rejected"]);
export const speciesRoleEnum = pgEnum("species_role", ["target","bait","prohibited"]);
export const speciesModeEnum = pgEnum("species_mode", ["include","exclude"]);
export const speciesScopeEnum = pgEnum("species_scope", ["all","listed"]);
export const targetTypeEnum = pgEnum("target_type", ["water_body","reach","zone","statewide","authority_territory"]);
export const targetModeEnum = pgEnum("target_mode", ["include","exclude"]);
export const sourceRoleEnum = pgEnum("source_role", ["primary","corroborating","spatial","text","verification","superseded"]);
export const periodStatusEnum = pgEnum("period_status", ["open","closed","open_catch_release"]);
export const resetBasisEnum = pgEnum("reset_basis", ["calendar_year","license_year","regulation_year","season"]); // used by JSONB parameter validation (Zod), not as a column type
export const sublimitModeEnum = pgEnum("sublimit_mode", ["additive","carve_out"]); // used by JSONB parameter validation (Zod), not as a column type
export const licenseYearBasisEnum = pgEnum("license_year_basis", ["fixed_calendar","rolling_12mo","regulation_year"]);
export const auditActionEnum = pgEnum("audit_action", ["insert","update","delete"]);
